package com.foreign_trade.model;

public class Exporter {

    private int exporterId;
    private String firmName;
    private String iecNumber; // Mandatory and unique
    private String contactPerson;
    private String country;

    // --- Constructor ---
    // Full Constructor
    public Exporter(int exporterId, String firmName, String iecNumber, String contactPerson, String country) {
        this.exporterId = exporterId;
        this.firmName = firmName;
        this.iecNumber = iecNumber;
        this.contactPerson = contactPerson;
        this.country = country;
    }

    // Constructor for creating a new Exporter (ID is generated by DB)
    public Exporter(String firmName, String iecNumber, String contactPerson, String country) {
        this(-1, firmName, iecNumber, contactPerson, country);
    }

    // --- Getters and Setters ---
    public int getExporterId() { return exporterId; }
    public void setExporterId(int exporterId) { this.exporterId = exporterId; }

    public String getFirmName() { return firmName; }
    public void setFirmName(String firmName) { this.firmName = firmName; }

    public String getIecNumber() { return iecNumber; }
    public void setIecNumber(String iecNumber) { this.iecNumber = iecNumber; }

    public String getContactPerson() { return contactPerson; }
    public void setContactPerson(String contactPerson) { this.contactPerson = contactPerson; }

    public String getCountry() { return country; }
    public void setCountry(String country) { this.country = country; }
}
