package com.foreign_trade.model;

public class FAQ {

    private int faqId;
    private String question;
    private String answer;

    // --- Constructor ---
    public FAQ(int faqId, String question, String answer) {
        this.faqId = faqId;
        this.question = question;
        this.answer = answer;
    }

    // Constructor for new FAQ (ID generated by DB)
    public FAQ(String question, String answer) {
        this(-1, question, answer);
    }

    // --- Getters and Setters ---
    public int getFaqId() { return faqId; }
    public void setFaqId(int faqId) { this.faqId = faqId; }

    public String getQuestion() { return question; }
    public void setQuestion(String question) { this.question = question; }

    public String getAnswer() { return answer; }
    public void setAnswer(String answer) { this.answer = answer; }
}