package com.foreign_trade.model;

import java.time.LocalDate;

public class Invoice {

    public enum PaymentStatus {
        PENDING, PAID, OVERDUE
    }

    private int invoiceId;
    private int shipmentId; // Foreign Key to Shipment
    private double amount;
    private LocalDate paymentDate;
    private PaymentStatus paymentStatus;

    // --- Full Constructor ---
    public Invoice(int invoiceId, int shipmentId, double amount, LocalDate paymentDate, PaymentStatus paymentStatus) {
        this.invoiceId = invoiceId;
        this.shipmentId = shipmentId;
        this.amount = amount;
        this.paymentDate = paymentDate;
        this.paymentStatus = paymentStatus;
    }

    // Constructor for new Invoice (ID generated by DB, Status starts as PENDING)
    public Invoice(int shipmentId, double amount, LocalDate paymentDate) {
        // Initial status is PENDING unless a date is provided
        this( -1, shipmentId, amount, paymentDate, PaymentStatus.PENDING);
    }

    // --- Getters and Setters ---
    public int getInvoiceId() { return invoiceId; }
    public void setInvoiceId(int invoiceId) { this.invoiceId = invoiceId; }

    public int getShipmentId() { return shipmentId; }
    public void setShipmentId(int shipmentId) { this.shipmentId = shipmentId; }

    public double getAmount() { return amount; }
    public void setAmount(double amount) { this.amount = amount; }

    public LocalDate getPaymentDate() { return paymentDate; }
    public void setPaymentDate(LocalDate paymentDate) { this.paymentDate = paymentDate; }

    public PaymentStatus getPaymentStatus() { return paymentStatus; }
    public void setPaymentStatus(PaymentStatus paymentStatus) { this.paymentStatus = paymentStatus; }
}
