package com.foreign_trade.model;

import java.time.LocalDate;

public class License {

    private int licenseId;
    private int exporterId; // Foreign Key to Exporter
    private String licenseNumber;
    private LocalDate issueDate;
    private LocalDate expiryDate;
    private String signatureUrl; // Placeholder path to the digital signature file

    // --- Full Constructor (Used when retrieving from DB) ---
    public License(int licenseId, int exporterId, String licenseNumber, LocalDate issueDate,
                   LocalDate expiryDate, String signatureUrl) {
        this.licenseId = licenseId;
        this.exporterId = exporterId;
        this.licenseNumber = licenseNumber;
        this.issueDate = issueDate;
        this.expiryDate = expiryDate;
        this.signatureUrl = signatureUrl;
    }

    // --- Constructor for New License (ID is generated by DB) ---
    public License(int exporterId, String licenseNumber, LocalDate issueDate,
                   LocalDate expiryDate, String signatureUrl) {
        this(-1, exporterId, licenseNumber, issueDate, expiryDate, signatureUrl);
    }

    // --- Business Logic Helper ---
    /**
     * Checks if the current date is before the expiry date.
     * @return true if the license is still valid, false otherwise.
     */
    public boolean isValid() {
        return LocalDate.now().isBefore(this.expiryDate);
    }

    // --- Getters and Setters ---

    public int getLicenseId() { return licenseId; }
    public void setLicenseId(int licenseId) { this.licenseId = licenseId; }

    public int getExporterId() { return exporterId; }
    public void setExporterId(int exporterId) { this.exporterId = exporterId; }

    public String getLicenseNumber() { return licenseNumber; }
    public void setLicenseNumber(String licenseNumber) { this.licenseNumber = licenseNumber; }

    public LocalDate getIssueDate() { return issueDate; }
    public void setIssueDate(LocalDate issueDate) { this.issueDate = issueDate; }

    public LocalDate getExpiryDate() { return expiryDate; }
    public void setExpiryDate(LocalDate expiryDate) { this.expiryDate = expiryDate; }

    public String getSignatureUrl() { return signatureUrl; }
    public void setSignatureUrl(String signatureUrl) { this.signatureUrl = signatureUrl; }
}
